In [199]:
import math
import torch
import torch.optim as optim
import torch.tensor as tensor
import gpytorch
from matplotlib import pyplot as plt

# generate target function 

# demo optimization using auto diff and optim

In [161]:
x = torch.tensor([2.,3.], requires_grad=True)
for i in range(1000):
    optimizer = optim.SGD([x], lr=.01)
    optimizer.zero_grad()
    y = torch.norm(x)**2
    y.backward()

    def closure():
        optimizer.zero_grad()
        y = torch.norm(x)**2
        y.backward()
        return y
    optimizer.step(closure)
    if i % 100 == 0:
        print('iter ', i, 'loss:', y.item())

iter  0 loss: 13.0
iter  100 loss: 0.22864331305027008
iter  200 loss: 0.004021368455141783
iter  300 loss: 7.072763401083648e-05
iter  400 loss: 1.2439543297659839e-06
iter  500 loss: 2.1878609146597228e-08
iter  600 loss: 3.847998586437029e-10
iter  700 loss: 6.767842362920273e-12
iter  800 loss: 1.1903253719063728e-13
iter  900 loss: 2.093538702653227e-15


In [271]:
x = torch.autograd.Variable(torch.randn(1,3),requires_grad=True)
print(x)
x = tensor([[1,2.],[3,4]], requires_grad=True)
z,_= torch.max(x,0)
print(z)
z.backward()
print(x.grad)

tensor([[ 1.5582,  0.9454, -0.2261]], requires_grad=True)
tensor([3., 4.], grad_fn=<MaxBackward0>)


RuntimeError: grad can be implicitly created only for scalar outputs

In [307]:
def qEI(x, num_mc_samples=5):
    K = x @ x.t()
    print(K)
    L = K.cholesky()
    print(L)
    z = torch.randn(x.shape[0], num_mc_samples)
    A = torch.ones(x.shape[1], 1)
    mean = x @ A
    y = mean + L @ z
    print(y)
    y_max, _ = torch.max(y, 0)
    print(y_max)
    ei = torch.relu(y_max - 1)
    print(ei)
    return ei.mean()

x = tensor([[1,2.],[2.,3]], requires_grad=True)
l = qEI(x)
print(l)
l.backward()
print(x.grad)

tensor([[ 5.,  8.],
        [ 8., 13.]], grad_fn=<MmBackward>)
tensor([[2.2361, 0.0000],
        [3.5777, 0.4472]], grad_fn=<CholeskyBackward>)
tensor([[1.0413, 0.5582, 2.1230, 4.8519, 2.5466],
        [2.1207, 0.9586, 3.6302, 7.8001, 5.2618]], grad_fn=<AddBackward0>)
tensor([2.1207, 0.9586, 3.6302, 7.8001, 5.2618], grad_fn=<MaxBackward0>)
tensor([1.1207, 0.0000, 2.6302, 6.8001, 4.2618], grad_fn=<ReluBackward0>)
tensor(2.9626, grad_fn=<MeanBackward1>)
tensor([[-0.7348,  0.3674],
        [ 1.1874,  0.4626]])
